proxy-groups:
- name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  proxies:
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - â˜ï¸ CFWarp-A
  - DIRECT
  type: select
- interval: 3600
  name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  proxies:
  - â˜ï¸ CFWarp-A
  tolerance: 200
  type: url-test
  url: http://www.gstatic.com/generate_204
- name: ğŸŒ å›½å¤–åª’ä½“
  proxies:
  - ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  - ğŸ¯ å…¨çƒç›´è¿
  - â˜ï¸ CFWarp-A
  type: select
- name: ğŸ“² ç”µæŠ¥ä¿¡æ¯
  proxies:
  - ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  - ğŸ¯ å…¨çƒç›´è¿
  - â˜ï¸ CFWarp-A
  type: select
- name: â“‚ï¸ å¾®è½¯æœåŠ¡
  proxies:
  - ğŸ¯ å…¨çƒç›´è¿
  - ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  type: select
- name: ğŸ è‹¹æœæœåŠ¡
  proxies:
  - ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  - ğŸ¯ å…¨çƒç›´è¿
  type: select
- name: ğŸ“¢ è°·æ­ŒFCM
  proxies:
  - ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  - ğŸ¯ å…¨çƒç›´è¿
  type: select
- name: ğŸ¯ å…¨çƒç›´è¿
  proxies:
  - DIRECT
  - ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  type: select
- name: ğŸƒ åº”ç”¨å‡€åŒ–
  proxies:
  - REJECT
  - ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  type: select
- name: ğŸŸ æ¼ç½‘ä¹‹é±¼
  proxies:
  - ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  - ğŸ¯ å…¨çƒç›´è¿
  - â˜ï¸ CFWarp-A
  type: select
